name: Publish to JSR

on:
  push:
    branches:
      - master

jobs:
  build:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        mongo: ["4.4"]
    steps:
      - name: Setup Environment
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.x

      - name: Log versions
        run: |
          deno --version

      # Lint
      - name: Lint TS
        run: deno lint
      # Start MongoDB
      - name: Start MongoDB (Linux)
        uses: wbari/start-mongoDB@v0.2
        with:
          mongoDBVersion: ${{ matrix.mongo }}

      # Tests
      - name: Test Mongodb
        env:
          BASE_URL: mongodb://localhost:27017/test
        run: deno task test
      
      - name: Publish package
        run: deno publish 